name: my_Build

on:
  schedule:
    - cron: 6 */8 * * *
#  push:
#    branches:
#      - main
#  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
            java-version: '17'
            distribution: 'adopt'
            cache: gradle
  
      - name: Build With Gradle
        run: |
          chmod +x gradlew ./jar/genJar.sh 
          ./gradlew assembleRelease --no-daemon
          ./jar/genJar.sh
      # - name: Upload APK
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Spider
      #     path: 
      - name: Commit and push changes
        run: |
            git config --local user.email bglhcode@icloud.com
            git config --local user.name bgcode
            git pull
            git add ./jar/catvod_spider.jar.md5 ./jar/catvod_spider.jar
            git commit -m "更新jar包
            git push
